import { Flag, Gauge, Pencil, Plus, Tags, Trash2 } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useFinance } from '../../../app/providers/FinanceProvider';
import { goalTotal, limitProgress } from '../../finance/domain/financeSelectors';
import type { Category, CategoryKind, Currency, MonthlyLimit, SavingsGoal } from '../../finance/domain/models';
import { newId } from '../../finance/domain/models';
import { Card } from '../../../shared/components/Card';
import { MoneyValue } from '../../../shared/components/MoneyValue';
import { ProgressBar } from '../../../shared/components/ProgressBar';
import { ConfirmDialog, Modal } from '../../../shared/components/Modal';

type Tab = 'limits' | 'goals' | 'categories';

function LimitForm({ initial, onDone }: { initial?: MonthlyLimit; onDone: () => void }) {
  const { database, monthData, saveLimit } = useFinance();
  const [categoryId, setCategoryId] = useState(initial?.categoryId ?? database.categories.find((item) => item.kind === 'expense')?.id ?? 'other');
  const [amount, setAmount] = useState(initial?.amount ? String(initial.amount) : '');
  const [currency, setCurrency] = useState<Currency>(initial?.currency ?? 'ARS');
  const [error, setError] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); const value = Number(amount); if (!Number.isFinite(value) || value <= 0) return setError('Ingresá un límite mayor a cero.'); saveLimit({ id: initial?.id ?? newId(), categoryId, amount: value, currency }); onDone(); };
  return <form className="form-grid" onSubmit={submit}><label className="field--wide">Categoría<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}>{database.categories.filter((item) => item.kind === 'expense').map((item) => <option disabled={!initial && monthData.limits.some((limit) => limit.categoryId === item.id)} key={item.id} value={item.id}>{item.icon} {item.name}</option>)}</select></label><label>Importe límite<input autoFocus type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>Moneda<select value={currency} onChange={(event) => setCurrency(event.target.value as Currency)}><option value="ARS">ARS</option><option value="USD">USD</option></select></label>{error && <p className="form-error field--wide">{error}</p>}<div className="form-actions field--wide"><button type="button" className="button button--ghost" onClick={onDone}>Cancelar</button><button className="button button--primary">Guardar límite</button></div></form>;
}

function GoalForm({ initial, onDone }: { initial?: SavingsGoal; onDone: () => void }) {
  const { saveGoal } = useFinance();
  const [name, setName] = useState(initial?.name ?? ''); const [amount, setAmount] = useState(initial?.targetAmount ? String(initial.targetAmount) : ''); const [currency, setCurrency] = useState<Currency>(initial?.currency ?? 'ARS'); const [targetDate, setTargetDate] = useState(initial?.targetDate ?? ''); const [color, setColor] = useState(initial?.color ?? '#9b87d3'); const [error, setError] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); const value = Number(amount); if (!name.trim()) return setError('Ingresá un nombre.'); if (!Number.isFinite(value) || value <= 0) return setError('Ingresá un monto objetivo válido.'); saveGoal({ id: initial?.id ?? newId(), name: name.trim(), targetAmount: value, currency, targetDate: targetDate || undefined, color, contributions: initial?.contributions ?? [] }); onDone(); };
  return <form className="form-grid" onSubmit={submit}><label className="field--wide">Nombre<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ej. Mi casa" /></label><label>Monto objetivo<input type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>Moneda<select value={currency} onChange={(event) => setCurrency(event.target.value as Currency)}><option value="ARS">ARS</option><option value="USD">USD</option></select></label><label>Fecha objetivo (opcional)<input type="date" value={targetDate} onChange={(event) => setTargetDate(event.target.value)} /></label><label>Color<input className="color-input" type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label>{error && <p className="form-error field--wide">{error}</p>}<div className="form-actions field--wide"><button type="button" className="button button--ghost" onClick={onDone}>Cancelar</button><button className="button button--primary">Guardar objetivo</button></div></form>;
}

function CategoryForm({ initial, onDone }: { initial?: Category; onDone: () => void }) {
  const { saveCategory } = useFinance(); const [name, setName] = useState(initial?.name ?? ''); const [icon, setIcon] = useState(initial?.icon ?? '✨'); const [color, setColor] = useState(initial?.color ?? '#9b87d3'); const [kind, setKind] = useState<CategoryKind>(initial?.kind ?? 'expense'); const [error, setError] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return setError('Ingresá un nombre.'); saveCategory({ id: initial?.id ?? newId(), name: name.trim(), icon: icon.trim() || '•', color, kind }); onDone(); };
  return <form className="form-grid" onSubmit={submit}><label className="field--wide">Nombre<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ej. Mascotas" /></label><label>Ícono<input value={icon} onChange={(event) => setIcon(event.target.value)} maxLength={4} /></label><label>Color<input className="color-input" type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label><label className="field--wide">Usar para<select value={kind} onChange={(event) => setKind(event.target.value as CategoryKind)}><option value="expense">Gastos</option><option value="income">Ingresos</option><option value="saving">Ahorro</option><option value="investment">Inversiones</option><option value="all">Cualquier movimiento</option></select></label>{error && <p className="form-error field--wide">{error}</p>}<div className="form-actions field--wide"><button type="button" className="button button--ghost" onClick={onDone}>Cancelar</button><button className="button button--primary">Guardar categoría</button></div></form>;
}

export function PlanningPage() {
  const { database, monthData, deleteLimit, deleteGoal, deleteCategory, contributeToGoal } = useFinance();
  const [tab, setTab] = useState<Tab>('limits'); const [editingLimit, setEditingLimit] = useState<MonthlyLimit | null | undefined>(); const [editingGoal, setEditingGoal] = useState<SavingsGoal | null | undefined>(); const [editingCategory, setEditingCategory] = useState<Category | null | undefined>(); const [deleteTarget, setDeleteTarget] = useState<{ type: Tab; id: string } | null>(null); const [contributing, setContributing] = useState<SavingsGoal | null>(null); const [contribution, setContribution] = useState(''); const [contributionError, setContributionError] = useState('');
  const tabs = [{ id: 'limits' as const, label: 'Límites', icon: Gauge }, { id: 'goals' as const, label: 'Objetivos', icon: Flag }, { id: 'categories' as const, label: 'Categorías', icon: Tags }];
  const add = () => tab === 'limits' ? setEditingLimit(null) : tab === 'goals' ? setEditingGoal(null) : setEditingCategory(null);
  const confirmDelete = () => { if (!deleteTarget) return; if (deleteTarget.type === 'limits') deleteLimit(deleteTarget.id); else if (deleteTarget.type === 'goals') deleteGoal(deleteTarget.id); else deleteCategory(deleteTarget.id); };
  return <>
    <div className="page-heading"><div><p className="eyebrow">HÁBITOS Y METAS</p><h1>Planificación</h1><p>Definí límites, objetivos y categorías a tu manera.</p></div><button className="button button--primary" onClick={add}><Plus size={18} /> Agregar {tab === 'limits' ? 'límite' : tab === 'goals' ? 'objetivo' : 'categoría'}</button></div>
    <div className="filter-tabs planning-tabs">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon size={17} />{label}</button>)}</div>
    {tab === 'limits' && <div className="planning-grid">{monthData.limits.map((limit) => { const category = database.categories.find((item) => item.id === limit.categoryId); const progress = limitProgress(limit, monthData); return <Card key={limit.id} className="planning-card"><div className="planning-card__header"><span className="category-icon" style={{ background: `${category?.color}22` }}>{category?.icon}</span><div className="row-actions"><button className="icon-button" aria-label={`Editar límite ${category?.name}`} onClick={() => setEditingLimit(limit)}><Pencil size={17} /></button><button className="icon-button" aria-label={`Eliminar límite ${category?.name}`} onClick={() => setDeleteTarget({ type: 'limits', id: limit.id })}><Trash2 size={17} /></button></div></div><h2>{category?.name}</h2><div className="limit-values"><MoneyValue value={progress.spent} /><span>de <MoneyValue value={limit.amount} /></span></div><ProgressBar value={progress.percentage} color={category?.color} /><small>{Math.round(progress.percentage)}% usado · {progress.percentage > 100 ? 'límite superado suavemente' : progress.percentage >= 80 ? 'cerca del límite' : 'vas muy bien'}</small></Card>; })}</div>}
    {tab === 'goals' && <div className="planning-grid">{database.goals.map((goal) => { const total = goalTotal(goal.contributions); return <Card key={goal.id} className="planning-card goal-card"><div className="planning-card__header"><span className="category-icon" style={{ background: `${goal.color}22`, color: goal.color }}><Flag size={20} /></span><div className="row-actions"><button className="icon-button" aria-label={`Editar ${goal.name}`} onClick={() => setEditingGoal(goal)}><Pencil size={17} /></button><button className="icon-button" aria-label={`Eliminar ${goal.name}`} onClick={() => setDeleteTarget({ type: 'goals', id: goal.id })}><Trash2 size={17} /></button></div></div><h2>{goal.name}</h2><div className="limit-values"><MoneyValue value={total} currency={goal.currency} /><span>de <MoneyValue value={goal.targetAmount} currency={goal.currency} /></span></div><ProgressBar value={total / goal.targetAmount * 100} color={goal.color} /><div className="goal-footer"><small>{Math.round(total / goal.targetAmount * 100)}% completado{goal.targetDate ? ` · meta ${new Intl.DateTimeFormat('es-AR').format(new Date(`${goal.targetDate}T12:00:00`))}` : ''}</small><button className="text-button" onClick={() => { setContributing(goal); setContribution(''); }}>+ Aportar</button></div></Card>; })}</div>}
    {tab === 'categories' && <Card className="categories-list">{database.categories.map((category) => <div key={category.id} className="category-row"><span className="category-icon" style={{ background: `${category.color}22` }}>{category.icon}</span><div><strong>{category.name}</strong><small>{category.kind === 'all' ? 'Todos los movimientos' : category.kind === 'expense' ? 'Gastos' : category.kind === 'income' ? 'Ingresos' : category.kind === 'saving' ? 'Ahorro' : 'Inversiones'}</small></div><span className="color-swatch" style={{ background: category.color }} /><div className="row-actions"><button className="icon-button" aria-label={`Editar ${category.name}`} onClick={() => setEditingCategory(category)}><Pencil size={17} /></button><button className="icon-button" aria-label={`Eliminar ${category.name}`} onClick={() => setDeleteTarget({ type: 'categories', id: category.id })}><Trash2 size={17} /></button></div></div>)}</Card>}
    <Modal open={editingLimit !== undefined} title={editingLimit ? 'Editar límite' : 'Nuevo límite'} onClose={() => setEditingLimit(undefined)}><LimitForm initial={editingLimit ?? undefined} onDone={() => setEditingLimit(undefined)} /></Modal>
    <Modal open={editingGoal !== undefined} title={editingGoal ? 'Editar objetivo' : 'Nuevo objetivo'} onClose={() => setEditingGoal(undefined)}><GoalForm initial={editingGoal ?? undefined} onDone={() => setEditingGoal(undefined)} /></Modal>
    <Modal open={editingCategory !== undefined} title={editingCategory ? 'Editar categoría' : 'Nueva categoría'} onClose={() => setEditingCategory(undefined)}><CategoryForm initial={editingCategory ?? undefined} onDone={() => setEditingCategory(undefined)} /></Modal>
    <Modal open={!!contributing} title={`Aportar a ${contributing?.name ?? ''}`} onClose={() => setContributing(null)}><form className="form-grid" onSubmit={(event) => { event.preventDefault(); const value = Number(contribution); if (!Number.isFinite(value) || value <= 0) return setContributionError('Ingresá un aporte mayor a cero.'); if (contributing) contributeToGoal(contributing.id, value); setContributing(null); }}><label className="field--wide">Importe<input autoFocus type="number" min="1" value={contribution} onChange={(event) => setContribution(event.target.value)} /></label>{contributionError && <p className="form-error field--wide">{contributionError}</p>}<div className="form-actions field--wide"><button type="button" className="button button--ghost" onClick={() => setContributing(null)}>Cancelar</button><button className="button button--primary">Registrar aporte</button></div></form></Modal>
    <ConfirmDialog open={!!deleteTarget} message={deleteTarget?.type === 'categories' ? 'Los movimientos existentes conservarán su referencia histórica.' : 'Esta acción no se puede deshacer.'} onClose={() => setDeleteTarget(null)} onConfirm={confirmDelete} />
  </>;
}
